version: '3'
services:
  hospitalDb:
    image: mysql:latest
    container_name: hospitalDb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hospital_storage
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
